/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  DefaultReverseResolver,
  DefaultReverseResolverInterface,
} from "../DefaultReverseResolver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "input",
        type: "bytes32",
      },
    ],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class DefaultReverseResolver__factory {
  static readonly abi = _abi;
  static createInterface(): DefaultReverseResolverInterface {
    return new utils.Interface(_abi) as DefaultReverseResolverInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): DefaultReverseResolver {
    return new Contract(address, _abi, signerOrProvider) as DefaultReverseResolver;
  }
}
