/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IDefaultReverseResolver,
  IDefaultReverseResolverInterface,
} from "../IDefaultReverseResolver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "input",
        type: "bytes32",
      },
    ],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IDefaultReverseResolver__factory {
  static readonly abi = _abi;
  static createInterface(): IDefaultReverseResolverInterface {
    return new utils.Interface(_abi) as IDefaultReverseResolverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDefaultReverseResolver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IDefaultReverseResolver;
  }
}
