/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IMetadata, IMetadataInterface } from "../IMetadata";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "citizen",
        type: "address",
      },
    ],
    name: "getAvatar",
    outputs: [
      {
        internalType: "string",
        name: "avatar",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "citizen",
        type: "address",
      },
    ],
    name: "getImage",
    outputs: [
      {
        internalType: "string",
        name: "avatar",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IMetadata__factory {
  static readonly abi = _abi;
  static createInterface(): IMetadataInterface {
    return new utils.Interface(_abi) as IMetadataInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMetadata {
    return new Contract(address, _abi, signerOrProvider) as IMetadata;
  }
}
