/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISoulbound, ISoulboundInterface } from "../ISoulbound";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "citizen",
        type: "address",
      },
    ],
    name: "getId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "citizen",
        type: "address",
      },
    ],
    name: "getLink",
    outputs: [
      {
        internalType: "address",
        name: "issuer",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "citizen",
        type: "address",
      },
    ],
    name: "hasRole",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_soul",
        type: "address",
      },
      {
        internalType: "address",
        name: "_issuer",
        type: "address",
      },
    ],
    name: "issue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_soul",
        type: "address",
      },
      {
        internalType: "address",
        name: "_revoker",
        type: "address",
      },
    ],
    name: "revoke",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISoulbound__factory {
  static readonly abi = _abi;
  static createInterface(): ISoulboundInterface {
    return new utils.Interface(_abi) as ISoulboundInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ISoulbound {
    return new Contract(address, _abi, signerOrProvider) as ISoulbound;
  }
}
