/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface DataENSInterface extends utils.Interface {
  contractName: "DataENS";
  functions: {
    "count(address)": FunctionFragment;
    "getData(address)": FunctionFragment;
    "getMetadata(address)": FunctionFragment;
    "getTextField(address,string)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "count", values: [string]): string;
  encodeFunctionData(functionFragment: "getData", values: [string]): string;
  encodeFunctionData(functionFragment: "getMetadata", values: [string]): string;
  encodeFunctionData(functionFragment: "getTextField", values: [string, string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "renounceOwnership", values?: undefined): string;
  encodeFunctionData(functionFragment: "transferOwnership", values: [string]): string;

  decodeFunctionResult(functionFragment: "count", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getData", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMetadata", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTextField", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "renounceOwnership", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transferOwnership", data: BytesLike): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter = TypedEventFilter<OwnershipTransferredEvent>;

export interface DataENS extends BaseContract {
  contractName: "DataENS";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DataENSInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    count(_address: string, overrides?: CallOverrides): Promise<[BigNumber] & { count: BigNumber }>;

    getData(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[string[], string[]] & { keys: string[]; values: string[] }>;

    getMetadata(
      _address: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        node: string;
        name: string;
        resolver: string;
      }
    >;

    getTextField(_address: string, _key: string, overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  count(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

  getData(
    _address: string,
    overrides?: CallOverrides
  ): Promise<[string[], string[]] & { keys: string[]; values: string[] }>;

  getMetadata(
    _address: string,
    overrides?: CallOverrides
  ): Promise<[string, string, string] & { node: string; name: string; resolver: string }>;

  getTextField(_address: string, _key: string, overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    count(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

    getData(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[string[], string[]] & { keys: string[]; values: string[] }>;

    getMetadata(
      _address: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        node: string;
        name: string;
        resolver: string;
      }
    >;

    getTextField(_address: string, _key: string, overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(newOwner: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    count(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

    getData(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

    getMetadata(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

    getTextField(_address: string, _key: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    count(_address: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getData(_address: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMetadata(_address: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTextField(
      _address: string,
      _key: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
