/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type TransactionStruct = {
  to: string;
  gasLimit: BigNumberish;
  data: BytesLike;
};

export type TransactionStructOutput = [string, BigNumber, string] & {
  to: string;
  gasLimit: BigNumber;
  data: string;
};

export interface ERC20AllowanceInterface extends utils.Interface {
  contractName: "ERC20Allowance";
  functions: {
    "enforceCaveat(bytes,(address,uint256,bytes),bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "enforceCaveat",
    values: [BytesLike, TransactionStruct, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "enforceCaveat",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ERC20Allowance extends BaseContract {
  contractName: "ERC20Allowance";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ERC20AllowanceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    enforceCaveat(
      terms: BytesLike,
      transaction: TransactionStruct,
      delegationHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  enforceCaveat(
    terms: BytesLike,
    transaction: TransactionStruct,
    delegationHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    enforceCaveat(
      terms: BytesLike,
      transaction: TransactionStruct,
      delegationHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    enforceCaveat(
      terms: BytesLike,
      transaction: TransactionStruct,
      delegationHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    enforceCaveat(
      terms: BytesLike,
      transaction: TransactionStruct,
      delegationHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
