/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IMetadataInterface extends utils.Interface {
  contractName: "IMetadata";
  functions: {
    "getAvatar(address)": FunctionFragment;
    "getImage(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getAvatar", values: [string]): string;
  encodeFunctionData(functionFragment: "getImage", values: [string]): string;

  decodeFunctionResult(functionFragment: "getAvatar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getImage", data: BytesLike): Result;

  events: {};
}

export interface IMetadata extends BaseContract {
  contractName: "IMetadata";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMetadataInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getAvatar(
      citizen: string,
      overrides?: CallOverrides
    ): Promise<[string] & { avatar: string }>;

    getImage(
      citizen: string,
      overrides?: CallOverrides
    ): Promise<[string] & { avatar: string }>;
  };

  getAvatar(citizen: string, overrides?: CallOverrides): Promise<string>;

  getImage(citizen: string, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getAvatar(citizen: string, overrides?: CallOverrides): Promise<string>;

    getImage(citizen: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getAvatar(citizen: string, overrides?: CallOverrides): Promise<BigNumber>;

    getImage(citizen: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getAvatar(
      citizen: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getImage(
      citizen: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
