/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type CaveatStruct = { enforcer: string; terms: BytesLike };

export type CaveatStructOutput = [string, string] & {
  enforcer: string;
  terms: string;
};

export type DelegationStruct = {
  delegate: string;
  authority: BytesLike;
  caveats: CaveatStruct[];
};

export type DelegationStructOutput = [string, string, CaveatStructOutput[]] & {
  delegate: string;
  authority: string;
  caveats: CaveatStructOutput[];
};

export type EIP712DomainStruct = {
  name: string;
  version: string;
  chainId: BigNumberish;
  verifyingContract: string;
};

export type EIP712DomainStructOutput = [string, string, BigNumber, string] & {
  name: string;
  version: string;
  chainId: BigNumber;
  verifyingContract: string;
};

export type IntentionToRevokeStruct = { delegationHash: BytesLike };

export type IntentionToRevokeStructOutput = [string] & {
  delegationHash: string;
};

export type TransactionStruct = {
  to: string;
  gasLimit: BigNumberish;
  data: BytesLike;
};

export type TransactionStructOutput = [string, BigNumber, string] & {
  to: string;
  gasLimit: BigNumber;
  data: string;
};

export type SignedDelegationStruct = {
  delegation: DelegationStruct;
  signature: BytesLike;
};

export type SignedDelegationStructOutput = [DelegationStructOutput, string] & {
  delegation: DelegationStructOutput;
  signature: string;
};

export type InvocationStruct = {
  transaction: TransactionStruct;
  authority: SignedDelegationStruct[];
};

export type InvocationStructOutput = [
  TransactionStructOutput,
  SignedDelegationStructOutput[]
] & {
  transaction: TransactionStructOutput;
  authority: SignedDelegationStructOutput[];
};

export type ReplayProtectionStruct = {
  nonce: BigNumberish;
  queue: BigNumberish;
};

export type ReplayProtectionStructOutput = [BigNumber, BigNumber] & {
  nonce: BigNumber;
  queue: BigNumber;
};

export type InvocationsStruct = {
  batch: InvocationStruct[];
  replayProtection: ReplayProtectionStruct;
};

export type InvocationsStructOutput = [
  InvocationStructOutput[],
  ReplayProtectionStructOutput
] & {
  batch: InvocationStructOutput[];
  replayProtection: ReplayProtectionStructOutput;
};

export type SignedIntentionToRevokeStruct = {
  signature: BytesLike;
  intentionToRevoke: IntentionToRevokeStruct;
};

export type SignedIntentionToRevokeStructOutput = [
  string,
  IntentionToRevokeStructOutput
] & { signature: string; intentionToRevoke: IntentionToRevokeStructOutput };

export type SignedInvocationStruct = {
  invocations: InvocationsStruct;
  signature: BytesLike;
};

export type SignedInvocationStructOutput = [InvocationsStructOutput, string] & {
  invocations: InvocationsStructOutput;
  signature: string;
};

export interface RevocationEnforcerInterface extends utils.Interface {
  contractName: "RevocationEnforcer";
  functions: {
    "GET_CAVEAT_ARRAY_PACKETHASH((address,bytes)[])": FunctionFragment;
    "GET_CAVEAT_PACKETHASH((address,bytes))": FunctionFragment;
    "GET_DELEGATION_PACKETHASH((address,bytes32,(address,bytes)[]))": FunctionFragment;
    "GET_EIP712DOMAIN_PACKETHASH((string,string,uint256,address))": FunctionFragment;
    "GET_INTENTIONTOREVOKE_PACKETHASH((bytes32))": FunctionFragment;
    "GET_INVOCATIONS_PACKETHASH((((address,uint256,bytes),((address,bytes32,(address,bytes)[]),bytes)[])[],(uint256,uint256)))": FunctionFragment;
    "GET_INVOCATION_ARRAY_PACKETHASH(((address,uint256,bytes),((address,bytes32,(address,bytes)[]),bytes)[])[])": FunctionFragment;
    "GET_INVOCATION_PACKETHASH(((address,uint256,bytes),((address,bytes32,(address,bytes)[]),bytes)[]))": FunctionFragment;
    "GET_REPLAYPROTECTION_PACKETHASH((uint256,uint256))": FunctionFragment;
    "GET_SIGNEDDELEGATION_ARRAY_PACKETHASH(((address,bytes32,(address,bytes)[]),bytes)[])": FunctionFragment;
    "GET_SIGNEDDELEGATION_PACKETHASH(((address,bytes32,(address,bytes)[]),bytes))": FunctionFragment;
    "GET_SIGNEDINTENTIONTOREVOKE_PACKETHASH((bytes,(bytes32)))": FunctionFragment;
    "GET_SIGNEDINVOCATION_PACKETHASH(((((address,uint256,bytes),((address,bytes32,(address,bytes)[]),bytes)[])[],(uint256,uint256)),bytes))": FunctionFragment;
    "GET_TRANSACTION_PACKETHASH((address,uint256,bytes))": FunctionFragment;
    "contractInvoke(((address,uint256,bytes),((address,bytes32,(address,bytes)[]),bytes)[])[])": FunctionFragment;
    "domainHash()": FunctionFragment;
    "enforceCaveat(bytes,(address,uint256,bytes),bytes32)": FunctionFragment;
    "getDelegationTypedDataHash((address,bytes32,(address,bytes)[]))": FunctionFragment;
    "getEIP712DomainHash(string,string,uint256,address)": FunctionFragment;
    "getIntentionToRevokeTypedDataHash((bytes32))": FunctionFragment;
    "getInvocationsTypedDataHash((((address,uint256,bytes),((address,bytes32,(address,bytes)[]),bytes)[])[],(uint256,uint256)))": FunctionFragment;
    "invoke(((((address,uint256,bytes),((address,bytes32,(address,bytes)[]),bytes)[])[],(uint256,uint256)),bytes)[])": FunctionFragment;
    "multiNonce(address,uint256)": FunctionFragment;
    "revokeDelegation(((address,bytes32,(address,bytes)[]),bytes),(bytes,(bytes32)))": FunctionFragment;
    "verifyDelegationSignature(((address,bytes32,(address,bytes)[]),bytes))": FunctionFragment;
    "verifyIntentionToRevokeSignature((bytes,(bytes32)))": FunctionFragment;
    "verifyInvocationSignature(((((address,uint256,bytes),((address,bytes32,(address,bytes)[]),bytes)[])[],(uint256,uint256)),bytes))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "GET_CAVEAT_ARRAY_PACKETHASH",
    values: [CaveatStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "GET_CAVEAT_PACKETHASH",
    values: [CaveatStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "GET_DELEGATION_PACKETHASH",
    values: [DelegationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "GET_EIP712DOMAIN_PACKETHASH",
    values: [EIP712DomainStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "GET_INTENTIONTOREVOKE_PACKETHASH",
    values: [IntentionToRevokeStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "GET_INVOCATIONS_PACKETHASH",
    values: [InvocationsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "GET_INVOCATION_ARRAY_PACKETHASH",
    values: [InvocationStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "GET_INVOCATION_PACKETHASH",
    values: [InvocationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "GET_REPLAYPROTECTION_PACKETHASH",
    values: [ReplayProtectionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "GET_SIGNEDDELEGATION_ARRAY_PACKETHASH",
    values: [SignedDelegationStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "GET_SIGNEDDELEGATION_PACKETHASH",
    values: [SignedDelegationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "GET_SIGNEDINTENTIONTOREVOKE_PACKETHASH",
    values: [SignedIntentionToRevokeStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "GET_SIGNEDINVOCATION_PACKETHASH",
    values: [SignedInvocationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "GET_TRANSACTION_PACKETHASH",
    values: [TransactionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "contractInvoke",
    values: [InvocationStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "domainHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enforceCaveat",
    values: [BytesLike, TransactionStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDelegationTypedDataHash",
    values: [DelegationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getEIP712DomainHash",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntentionToRevokeTypedDataHash",
    values: [IntentionToRevokeStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvocationsTypedDataHash",
    values: [InvocationsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "invoke",
    values: [SignedInvocationStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "multiNonce",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDelegation",
    values: [SignedDelegationStruct, SignedIntentionToRevokeStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDelegationSignature",
    values: [SignedDelegationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyIntentionToRevokeSignature",
    values: [SignedIntentionToRevokeStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyInvocationSignature",
    values: [SignedInvocationStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "GET_CAVEAT_ARRAY_PACKETHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GET_CAVEAT_PACKETHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GET_DELEGATION_PACKETHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GET_EIP712DOMAIN_PACKETHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GET_INTENTIONTOREVOKE_PACKETHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GET_INVOCATIONS_PACKETHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GET_INVOCATION_ARRAY_PACKETHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GET_INVOCATION_PACKETHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GET_REPLAYPROTECTION_PACKETHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GET_SIGNEDDELEGATION_ARRAY_PACKETHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GET_SIGNEDDELEGATION_PACKETHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GET_SIGNEDINTENTIONTOREVOKE_PACKETHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GET_SIGNEDINVOCATION_PACKETHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GET_TRANSACTION_PACKETHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractInvoke",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "domainHash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "enforceCaveat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDelegationTypedDataHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEIP712DomainHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIntentionToRevokeTypedDataHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInvocationsTypedDataHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "invoke", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multiNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeDelegation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDelegationSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyIntentionToRevokeSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyInvocationSignature",
    data: BytesLike
  ): Result;

  events: {
    "DelegationTriggered(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DelegationTriggered"): EventFragment;
}

export type DelegationTriggeredEvent = TypedEvent<
  [string, string],
  { principal: string; agent: string }
>;

export type DelegationTriggeredEventFilter =
  TypedEventFilter<DelegationTriggeredEvent>;

export interface RevocationEnforcer extends BaseContract {
  contractName: "RevocationEnforcer";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RevocationEnforcerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    GET_CAVEAT_ARRAY_PACKETHASH(
      _input: CaveatStruct[],
      overrides?: CallOverrides
    ): Promise<[string]>;

    GET_CAVEAT_PACKETHASH(
      _input: CaveatStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    GET_DELEGATION_PACKETHASH(
      _input: DelegationStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    GET_EIP712DOMAIN_PACKETHASH(
      _input: EIP712DomainStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    GET_INTENTIONTOREVOKE_PACKETHASH(
      _input: IntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    GET_INVOCATIONS_PACKETHASH(
      _input: InvocationsStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    GET_INVOCATION_ARRAY_PACKETHASH(
      _input: InvocationStruct[],
      overrides?: CallOverrides
    ): Promise<[string]>;

    GET_INVOCATION_PACKETHASH(
      _input: InvocationStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    GET_REPLAYPROTECTION_PACKETHASH(
      _input: ReplayProtectionStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    GET_SIGNEDDELEGATION_ARRAY_PACKETHASH(
      _input: SignedDelegationStruct[],
      overrides?: CallOverrides
    ): Promise<[string]>;

    GET_SIGNEDDELEGATION_PACKETHASH(
      _input: SignedDelegationStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    GET_SIGNEDINTENTIONTOREVOKE_PACKETHASH(
      _input: SignedIntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    GET_SIGNEDINVOCATION_PACKETHASH(
      _input: SignedInvocationStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    GET_TRANSACTION_PACKETHASH(
      _input: TransactionStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    contractInvoke(
      batch: InvocationStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    domainHash(overrides?: CallOverrides): Promise<[string]>;

    enforceCaveat(
      terms: BytesLike,
      transaction: TransactionStruct,
      delegationHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getDelegationTypedDataHash(
      delegation: DelegationStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getEIP712DomainHash(
      contractName: string,
      version: string,
      chainId: BigNumberish,
      verifyingContract: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getIntentionToRevokeTypedDataHash(
      intentionToRevoke: IntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getInvocationsTypedDataHash(
      invocations: InvocationsStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    invoke(
      signedInvocations: SignedInvocationStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    multiNonce(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    revokeDelegation(
      signedDelegation: SignedDelegationStruct,
      signedIntentionToRevoke: SignedIntentionToRevokeStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    verifyDelegationSignature(
      signedDelegation: SignedDelegationStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    verifyIntentionToRevokeSignature(
      signedIntentionToRevoke: SignedIntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    verifyInvocationSignature(
      signedInvocation: SignedInvocationStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  GET_CAVEAT_ARRAY_PACKETHASH(
    _input: CaveatStruct[],
    overrides?: CallOverrides
  ): Promise<string>;

  GET_CAVEAT_PACKETHASH(
    _input: CaveatStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  GET_DELEGATION_PACKETHASH(
    _input: DelegationStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  GET_EIP712DOMAIN_PACKETHASH(
    _input: EIP712DomainStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  GET_INTENTIONTOREVOKE_PACKETHASH(
    _input: IntentionToRevokeStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  GET_INVOCATIONS_PACKETHASH(
    _input: InvocationsStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  GET_INVOCATION_ARRAY_PACKETHASH(
    _input: InvocationStruct[],
    overrides?: CallOverrides
  ): Promise<string>;

  GET_INVOCATION_PACKETHASH(
    _input: InvocationStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  GET_REPLAYPROTECTION_PACKETHASH(
    _input: ReplayProtectionStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  GET_SIGNEDDELEGATION_ARRAY_PACKETHASH(
    _input: SignedDelegationStruct[],
    overrides?: CallOverrides
  ): Promise<string>;

  GET_SIGNEDDELEGATION_PACKETHASH(
    _input: SignedDelegationStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  GET_SIGNEDINTENTIONTOREVOKE_PACKETHASH(
    _input: SignedIntentionToRevokeStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  GET_SIGNEDINVOCATION_PACKETHASH(
    _input: SignedInvocationStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  GET_TRANSACTION_PACKETHASH(
    _input: TransactionStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  contractInvoke(
    batch: InvocationStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  domainHash(overrides?: CallOverrides): Promise<string>;

  enforceCaveat(
    terms: BytesLike,
    transaction: TransactionStruct,
    delegationHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getDelegationTypedDataHash(
    delegation: DelegationStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  getEIP712DomainHash(
    contractName: string,
    version: string,
    chainId: BigNumberish,
    verifyingContract: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getIntentionToRevokeTypedDataHash(
    intentionToRevoke: IntentionToRevokeStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  getInvocationsTypedDataHash(
    invocations: InvocationsStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  invoke(
    signedInvocations: SignedInvocationStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  multiNonce(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  revokeDelegation(
    signedDelegation: SignedDelegationStruct,
    signedIntentionToRevoke: SignedIntentionToRevokeStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  verifyDelegationSignature(
    signedDelegation: SignedDelegationStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  verifyIntentionToRevokeSignature(
    signedIntentionToRevoke: SignedIntentionToRevokeStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  verifyInvocationSignature(
    signedInvocation: SignedInvocationStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    GET_CAVEAT_ARRAY_PACKETHASH(
      _input: CaveatStruct[],
      overrides?: CallOverrides
    ): Promise<string>;

    GET_CAVEAT_PACKETHASH(
      _input: CaveatStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    GET_DELEGATION_PACKETHASH(
      _input: DelegationStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    GET_EIP712DOMAIN_PACKETHASH(
      _input: EIP712DomainStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    GET_INTENTIONTOREVOKE_PACKETHASH(
      _input: IntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    GET_INVOCATIONS_PACKETHASH(
      _input: InvocationsStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    GET_INVOCATION_ARRAY_PACKETHASH(
      _input: InvocationStruct[],
      overrides?: CallOverrides
    ): Promise<string>;

    GET_INVOCATION_PACKETHASH(
      _input: InvocationStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    GET_REPLAYPROTECTION_PACKETHASH(
      _input: ReplayProtectionStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    GET_SIGNEDDELEGATION_ARRAY_PACKETHASH(
      _input: SignedDelegationStruct[],
      overrides?: CallOverrides
    ): Promise<string>;

    GET_SIGNEDDELEGATION_PACKETHASH(
      _input: SignedDelegationStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    GET_SIGNEDINTENTIONTOREVOKE_PACKETHASH(
      _input: SignedIntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    GET_SIGNEDINVOCATION_PACKETHASH(
      _input: SignedInvocationStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    GET_TRANSACTION_PACKETHASH(
      _input: TransactionStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    contractInvoke(
      batch: InvocationStruct[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    domainHash(overrides?: CallOverrides): Promise<string>;

    enforceCaveat(
      terms: BytesLike,
      transaction: TransactionStruct,
      delegationHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getDelegationTypedDataHash(
      delegation: DelegationStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    getEIP712DomainHash(
      contractName: string,
      version: string,
      chainId: BigNumberish,
      verifyingContract: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getIntentionToRevokeTypedDataHash(
      intentionToRevoke: IntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    getInvocationsTypedDataHash(
      invocations: InvocationsStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    invoke(
      signedInvocations: SignedInvocationStruct[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    multiNonce(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    revokeDelegation(
      signedDelegation: SignedDelegationStruct,
      signedIntentionToRevoke: SignedIntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    verifyDelegationSignature(
      signedDelegation: SignedDelegationStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    verifyIntentionToRevokeSignature(
      signedIntentionToRevoke: SignedIntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    verifyInvocationSignature(
      signedInvocation: SignedInvocationStruct,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "DelegationTriggered(address,address)"(
      principal?: null,
      agent?: string | null
    ): DelegationTriggeredEventFilter;
    DelegationTriggered(
      principal?: null,
      agent?: string | null
    ): DelegationTriggeredEventFilter;
  };

  estimateGas: {
    GET_CAVEAT_ARRAY_PACKETHASH(
      _input: CaveatStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GET_CAVEAT_PACKETHASH(
      _input: CaveatStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GET_DELEGATION_PACKETHASH(
      _input: DelegationStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GET_EIP712DOMAIN_PACKETHASH(
      _input: EIP712DomainStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GET_INTENTIONTOREVOKE_PACKETHASH(
      _input: IntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GET_INVOCATIONS_PACKETHASH(
      _input: InvocationsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GET_INVOCATION_ARRAY_PACKETHASH(
      _input: InvocationStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GET_INVOCATION_PACKETHASH(
      _input: InvocationStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GET_REPLAYPROTECTION_PACKETHASH(
      _input: ReplayProtectionStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GET_SIGNEDDELEGATION_ARRAY_PACKETHASH(
      _input: SignedDelegationStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GET_SIGNEDDELEGATION_PACKETHASH(
      _input: SignedDelegationStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GET_SIGNEDINTENTIONTOREVOKE_PACKETHASH(
      _input: SignedIntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GET_SIGNEDINVOCATION_PACKETHASH(
      _input: SignedInvocationStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GET_TRANSACTION_PACKETHASH(
      _input: TransactionStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contractInvoke(
      batch: InvocationStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    domainHash(overrides?: CallOverrides): Promise<BigNumber>;

    enforceCaveat(
      terms: BytesLike,
      transaction: TransactionStruct,
      delegationHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getDelegationTypedDataHash(
      delegation: DelegationStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEIP712DomainHash(
      contractName: string,
      version: string,
      chainId: BigNumberish,
      verifyingContract: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIntentionToRevokeTypedDataHash(
      intentionToRevoke: IntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getInvocationsTypedDataHash(
      invocations: InvocationsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    invoke(
      signedInvocations: SignedInvocationStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    multiNonce(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    revokeDelegation(
      signedDelegation: SignedDelegationStruct,
      signedIntentionToRevoke: SignedIntentionToRevokeStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    verifyDelegationSignature(
      signedDelegation: SignedDelegationStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyIntentionToRevokeSignature(
      signedIntentionToRevoke: SignedIntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyInvocationSignature(
      signedInvocation: SignedInvocationStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    GET_CAVEAT_ARRAY_PACKETHASH(
      _input: CaveatStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GET_CAVEAT_PACKETHASH(
      _input: CaveatStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GET_DELEGATION_PACKETHASH(
      _input: DelegationStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GET_EIP712DOMAIN_PACKETHASH(
      _input: EIP712DomainStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GET_INTENTIONTOREVOKE_PACKETHASH(
      _input: IntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GET_INVOCATIONS_PACKETHASH(
      _input: InvocationsStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GET_INVOCATION_ARRAY_PACKETHASH(
      _input: InvocationStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GET_INVOCATION_PACKETHASH(
      _input: InvocationStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GET_REPLAYPROTECTION_PACKETHASH(
      _input: ReplayProtectionStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GET_SIGNEDDELEGATION_ARRAY_PACKETHASH(
      _input: SignedDelegationStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GET_SIGNEDDELEGATION_PACKETHASH(
      _input: SignedDelegationStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GET_SIGNEDINTENTIONTOREVOKE_PACKETHASH(
      _input: SignedIntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GET_SIGNEDINVOCATION_PACKETHASH(
      _input: SignedInvocationStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GET_TRANSACTION_PACKETHASH(
      _input: TransactionStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contractInvoke(
      batch: InvocationStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    domainHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    enforceCaveat(
      terms: BytesLike,
      transaction: TransactionStruct,
      delegationHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getDelegationTypedDataHash(
      delegation: DelegationStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEIP712DomainHash(
      contractName: string,
      version: string,
      chainId: BigNumberish,
      verifyingContract: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIntentionToRevokeTypedDataHash(
      intentionToRevoke: IntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getInvocationsTypedDataHash(
      invocations: InvocationsStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    invoke(
      signedInvocations: SignedInvocationStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    multiNonce(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    revokeDelegation(
      signedDelegation: SignedDelegationStruct,
      signedIntentionToRevoke: SignedIntentionToRevokeStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    verifyDelegationSignature(
      signedDelegation: SignedDelegationStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyIntentionToRevokeSignature(
      signedIntentionToRevoke: SignedIntentionToRevokeStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyInvocationSignature(
      signedInvocation: SignedInvocationStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
